### ISSUE TITLE
[ADD] Detail(대기중) View 껍데기 구현

### ISSUE THREAD

**Issue by MMMIIIN** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#1]
## 💡 Issue

Detail(대기중) 껍데기 UI를 만듭니다.

## 📝  todo
- [x] 타이틀
- [x] 진행 기간
- [x] 함께하는 친구들
- [x] 방 코드 복사 토스트 형식
- [ ] 설정 버튼 
- [x] 시작 버튼

**Comment by dangsal** [comment]
케미도 화이팅^___^

**Comment by MMMIIIN** [comment]
설정 버튼은 듀나가 만들어준 네이게이션바 풀 받고 구현하겠습니다
