### ISSUE TITLE
[CHORE] 받은 쪽지, 보낸 쪽지 반대로 변경

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#154]
## 💡 Issue

받은 쪽지, 보낸 쪽지의 Segment Control를 반대로 변경합니다.

## 📝  todo
- [x] Segment Control 반대로 변경

**Comment by dangsal** [comment]
여기에서 UX 라이팅 바뀐점 고려해주세요!
