### ISSUE TITLE
[CHORE] 릴리즈 서버 변경

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#306]
## 💡 Issue

릴리즈 서버를 변경합니다.

## 📝  todo
- [x] production 서버로 변경

**Comment by MMMIIIN** [comment]
제..제...제...제가요...??

**Comment by YoonAh-dev** [comment]
@MMMIIIN 천재 개발자니깐 저는 믿습니다. 이정도는 케미한테 GUM이죠?

**Comment by MMMIIIN** [comment]
@YoonAh-dev 심사중에 앱 버전 교체할 수 있나요 ??
