### ISSUE TITLE
[REFACTOR] Presentation Layer 로 옮기면서 ViewModel 수정

### ISSUE THREAD

**Issue by dangsal** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#547]
## 💡 Issue

- 현재 제가 만든 뷰들이 Presentation 레이어에 없어서 옮길 예정입니다. 
- 옮기면서 ViewModel 에 보이는 자잘쓰 를 변경할 예정입니다. 

## 📝  todo
- [ ] todo !

**Comment by YoonAh-dev** [comment]
이슈 이름이 요상쓰..
