### ISSUE TITLE
[BUG] CreateRoom View 2가지 Bug

### ISSUE THREAD

**Issue by MMMIIIN** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#94]
# 🐞 버그 설명
| 문제 발생 일시 |  발생 위치  | 발생 조건 |
| --- | --- | --- | 
| 22.06.28 | 방 생성 View | 메인에서 방 생성하기 버튼을 눌렀을 때 발생 | 

## 증상 

1. 뒤로가기 버튼이 두개로 보여요
- 위에 뒤로가기 버튼은 dismiss고 아래 이전버튼은 방 생성 내에서 UIView가 바뀌는걸 이전 View로 가는 기능인데 수정이 필요해 보이네요
2. 다음을 누른만큼 스택이 쌓이고 그 만큼 이전을 눌러야 돌아가요

## 스크린샷

![Jun-28-2022 22-50-09](https://user-images.githubusercontent.com/78677571/176195622-3479fc32-972d-4e85-b9a8-3199f2b04549.gif)

도와줘요 @dangsal

**Comment by dangsal** [comment]
어라라???  뭔가 같이 만들다가 헷갈렸나봐욬ㅋㅋㅋㅋㅋ

**Comment by MMMIIIN** [comment]
> 어라라??? 뭔가 같이 만들다가 헷갈렸나봐욬ㅋㅋㅋㅋㅋ

BaseViewController에 있는 네비게이션바가 같이 딸려온거 같아요 ! 
X 표시가 사실 dismiss기능인 것 같아서 BaseViewController에있는 네비게이션바만 숨기면 될 것 같아요 ^_______^

**Comment by dangsal** [comment]
너무 예전이라 .... 풀 땡겨올때 충돌 많이 날까봐 새로 이슈 팠습니다! close 부탁드려용ㅎㅎ
