### ISSUE TITLE
[BUG] assign-reviewer error

### ISSUE THREAD

**Issue by MMMIIIN** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#96]
# 🐞 버그 설명
| 문제 발생 일시 |  발생 위치  | 발생 조건 |
| --- | --- | --- | 
| 22.07.01 | github | PR생성 | 

## 증상 

- 리뷰어가 자동으로 추가가 안되네요
- 링고와 주디를 자동 리뷰어 추가하는걸 빼면서 발생한 문제 같습니다.

**Comment by dangsal** [comment]
저는 잘 되는거 같은데요..!!!!

**Comment by MMMIIIN** [comment]
> 저는 잘 되는거 같은데요..!!!!

그렇군요 ! 일시적인 문제였나봅니다 ^______^
